openapi: 3.0.0
info:
  title: "Devloom - Programming Education"
  description: "Devloom is a modular, scalable API designed for building a modern programming education platform. Built with TypeScript + Express + MongoDB + Zod, focusing on clarity, structure, and long‑term maintainability."
  version: 1.0.0
servers:
  - url: 'http://localhost:3000/api/v1/'
    description: base url
tags:
  - name: "Auth"
    description: "User Auth"
  - name: "Category"
    description: "category of courses"
  - name: "Course"
    description: "courses"
  - name: "Lesson"
    description: "lessons of Course"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "JWT access token"
security:
  - bearerAuth: [ ]
paths:
  # <=== Auth route ===>
  # Signup new user
  /auth/signup:
    $ref: "./path/auth.yaml#/signup"
    # Login with email and password
  /auth/login:
    $ref: "./path/auth.yaml#/login"
    # get safe-information user
  /auth/getMe:
    $ref: "./path/auth.yaml#/getMe"
    # logout system
  /auth/logout:
    $ref: "./path/auth.yaml#/logout"
    # refresh (get new accessToken)
  /auth/refresh:
    $ref: "./path/auth.yaml#/refresh"
    # get all users list
  /auth/users:
    $ref: "./path/auth.yaml#/users"
    # get one user with id or email
  /auth/user:
    $ref: "./path/auth.yaml#/user"
  /auth/user/{id}/role:
    $ref: "./path/auth.yaml#/userRole"
  /auth/ban:
    $ref: "./path/auth.yaml#/banUser"

  # <=== Category route ===>
  # get all and create one category
  /category:
    $ref: "./path/category.yaml#/category"
  # get, delete and edit one category
  /category/{id}:
    $ref: "./path/category.yaml#/oneCategory"